<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="FYP2020-Swarm-Quadruped">

    <xacro:property name="shoul_len" value="0.035" />
    <xacro:property name="thigh_len" value="0.05" />
    <xacro:property name="shank_len" value="0.05" />
    <xacro:property name="link_radius" value="0.0025"/>
    <xacro:property name="feet_radius" value="0.0025"/>
    <xacro:property name="pi" value="3.1415" />
    <xacro:property name="body_len" value="0.10" />
    <xacro:property name="body_width" value="0.05" />
    <xacro:property name="body_height" value="0.02" />
    <xacro:property name="damping_value" value="10" />
    <xacro:property name="friction_value" value="0.1" />

    <material name="red">
        <color rgba="255 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="0 0 0 1"/>
    </material>


  <!--Main Body-->
    <link name="base_link">
       <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
             <box size="${body_len} ${body_width} ${body_height}" />
          </geometry>
          <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "10"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>

       <collision>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
            <box size="${body_len} ${body_width} ${body_height}" />
         </geometry>
       </collision>
    </link>



  <!--Left Front Leg-->
    <link name="shoulder_link_lf">
       <collision>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*1.0*shoul_len} 0"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shoul_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*1.0*shoul_len} 0"/>
         <geometry>
            <cylinder length="${shoul_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="shoulder_joint_lf" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="${0.5*body_len*1.0} ${1.0*0.005} 0"/>
      <axis xyz="1 0 0"/>
      <parent link="base_link"/>
      <child link="shoulder_link_lf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="thigh_link_lf">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${thigh_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder length="${thigh_len}" radius="${link_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="elbow_joint_lf" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 ${1.0*shoul_len} 0"/>
      <axis xyz="0 1 0"/>
      <parent link="shoulder_link_lf"/>
      <child link="thigh_link_lf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="shank_link_lf">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shank_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder length="${shank_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="wrist_joint_lf" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 0 ${-thigh_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="thigh_link_lf"/>
      <child link="shank_link_lf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="feet_link_lf">
       <collision>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "0.2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="ankle_joint_lf" type="fixed">
      <origin xyz="0 0 ${-shank_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="shank_link_lf"/>
      <child link="feet_link_lf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>



  <!--Right Front Leg-->
    <link name="shoulder_link_rf">
       <collision>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*-1.0*shoul_len} 0"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shoul_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*-1.0*shoul_len} 0"/>
         <geometry>
            <cylinder length="${shoul_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="shoulder_joint_rf" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="${0.5*body_len*1.0} ${-1.0*0.005} 0"/>
      <axis xyz="1 0 0"/>
      <parent link="base_link"/>
      <child link="shoulder_link_rf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="thigh_link_rf">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${thigh_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder length="${thigh_len}" radius="${link_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="elbow_joint_rf" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 ${-1.0*shoul_len} 0"/>
      <axis xyz="0 1 0"/>
      <parent link="shoulder_link_rf"/>
      <child link="thigh_link_rf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="shank_link_rf">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shank_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder length="${shank_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="wrist_joint_rf" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 0 ${-thigh_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="thigh_link_rf"/>
      <child link="shank_link_rf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="feet_link_rf">
       <collision>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "0.2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="ankle_joint_rf" type="fixed">
      <origin xyz="0 0 ${-shank_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="shank_link_rf"/>
      <child link="feet_link_rf"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>



  <!--Left Back Leg-->
    <link name="shoulder_link_lb">
       <collision>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*1.0*shoul_len} 0"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shoul_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*1.0*shoul_len} 0"/>
         <geometry>
            <cylinder length="${shoul_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="shoulder_joint_lb" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="${0.5*body_len*-1.0} ${1.0*0.005} 0"/>
      <axis xyz="1 0 0"/>
      <parent link="base_link"/>
      <child link="shoulder_link_lb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="thigh_link_lb">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${thigh_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder length="${thigh_len}" radius="${link_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="elbow_joint_lb" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 ${1.0*shoul_len} 0"/>
      <axis xyz="0 1 0"/>
      <parent link="shoulder_link_lb"/>
      <child link="thigh_link_lb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="shank_link_lb">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shank_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder length="${shank_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="wrist_joint_lb" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 0 ${-thigh_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="thigh_link_lb"/>
      <child link="shank_link_lb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="feet_link_lb">
       <collision>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "0.2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="ankle_joint_lb" type="fixed">
      <origin xyz="0 0 ${-shank_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="shank_link_lb"/>
      <child link="feet_link_lb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>



  <!--Right Back Leg-->
    <link name="shoulder_link_rb">
       <collision>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*-1.0*shoul_len} 0"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shoul_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="${pi*0.5} 0 0" xyz="0 ${0.5*-1.0*shoul_len} 0"/>
         <geometry>
            <cylinder length="${shoul_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="shoulder_joint_rb" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="${0.5*body_len*-1.0} ${-1.0*0.005} 0"/>
      <axis xyz="1 0 0"/>
      <parent link="base_link"/>
      <child link="shoulder_link_rb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="thigh_link_rb">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${thigh_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*thigh_len}"/>
         <geometry>
            <cylinder length="${thigh_len}" radius="${link_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="elbow_joint_rb" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 ${-1.0*shoul_len} 0"/>
      <axis xyz="0 1 0"/>
      <parent link="shoulder_link_rb"/>
      <child link="thigh_link_rb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="shank_link_rb">
       <collision>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder radius="${link_radius}" length="${shank_len}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 ${-0.5*shank_len}"/>
         <geometry>
            <cylinder length="${shank_len}" radius="${link_radius}"/>
         </geometry>
         <material name="red"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="wrist_joint_rb" type="revolute">
      <limit effort="100.0" lower="${-0.5*pi}" upper="${0.5*pi}" velocity="0.5"/>
      <origin xyz="0 0 ${-thigh_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="thigh_link_rb"/>
      <child link="shank_link_rb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>


    <link name="feet_link_rb">
       <collision>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
       </collision>

       <visual>
         <origin rpy="0 0 0" xyz="0 0 0"/>
         <geometry>
            <sphere radius="${feet_radius}"/>
         </geometry>
         <material name="white"/>
       </visual>

       <inertial>
         <origin xyz="0 0 0" rpy="0 0 0"/>
         <mass value = "0.2"/>
         <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
       </inertial>
    </link>

    <joint name="ankle_joint_rb" type="fixed">
      <origin xyz="0 0 ${-shank_len}"/>
      <axis xyz="0 1 0"/>
      <parent link="shank_link_rb"/>
      <child link="feet_link_rb"/>
      <dynamics damping="${damping_value}" friction="${friction_value}"/>
    </joint>



  <!--gazebo plugin-->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
           <robotNamespace>/FYP2020-Swarm-Quadruped</robotNamespace>
	   <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>



  <!--transmission tags for the links-->
    <transmission name="shoulder_joint_lf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="shoulder_joint_lf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="elbow_joint_lf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="elbow_joint_lf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor2">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="wrist_joint_lf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wrist_joint_lf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor3">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="ankle_joint_lf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="ankle_joint_lf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor4">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="shoulder_joint_rf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="shoulder_joint_rf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor5">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="elbow_joint_rf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="elbow_joint_rf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor6">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="wrist_joint_rf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wrist_joint_rf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor7">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="ankle_joint_rf_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="ankle_joint_rf">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor8">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="shoulder_joint_lb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="shoulder_joint_lb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor9">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="elbow_joint_lb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="elbow_joint_lb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor10">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="wrist_joint_lb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wrist_joint_lb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor11">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="ankle_joint_lb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="ankle_joint_lb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor12">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="shoulder_joint_rb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="shoulder_joint_rb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>13</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="elbow_joint_rb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="elbow_joint_rb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor14">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="wrist_joint_rb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wrist_joint_rb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor15">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="ankle_joint_rb_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="ankle_joint_rb">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor16">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
</robot>
