FYP2020-Swarm-Quadruped:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    shoulder_joint_lf_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_joint_lf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    shoulder_joint_rf_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_joint_rf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    shoulder_joint_lb_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_joint_lb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    shoulder_joint_rb_position_controller:
      type: effort_controllers/JointPositionController
      joint: shoulder_joint_rb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    elbow_joint_lf_position_controller:
      type: effort_controllers/JointPositionController
      joint: elbow_joint_lf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    elbow_joint_rf_position_controller:
      type: effort_controllers/JointPositionController
      joint: elbow_joint_rf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    elbow_joint_lb_position_controller:
      type: effort_controllers/JointPositionController
      joint: elbow_joint_lb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    elbow_joint_rb_position_controller:
      type: effort_controllers/JointPositionController
      joint: elbow_joint_rb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    wrist_joint_lf_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_joint_lf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    wrist_joint_rf_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_joint_rf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    wrist_joint_lb_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_joint_lb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    wrist_joint_rb_position_controller:
      type: effort_controllers/JointPositionController
      joint: wrist_joint_rb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    ankle_joint_lf_position_controller:
      type: effort_controllers/JointPositionController
      joint: ankle_joint_lf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    ankle_joint_rf_position_controller:
      type: effort_controllers/JointPositionController
      joint: ankle_joint_rf
      pid: {p: 1.0, i: 1.0, d: 0.0}
    ankle_joint_lb_position_controller:
      type: effort_controllers/JointPositionController
      joint: ankle_joint_lb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    ankle_joint_rb_position_controller:
      type: effort_controllers/JointPositionController
      joint: ankle_joint_rb
      pid: {p: 1.0, i: 1.0, d: 0.0}
    # To add more just add them here as the first one
